name = "pip-by-pip"
compatibility_date = "2026-08-12"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js/index.js"

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "pip-by-pip"
database_id = "4726c40d-1fca-4ffb-b2fd-723a3f60048b"
