#!/usr/bin/env node
/**
 * Creates the sign-in codes for Pip by Pip and writes the SQL that installs
 * them. Codes are never stored anywhere in plain text, so this script prints
 * them once. Write them down.
 *
 *   node scripts/make-codes.mjs "Dheepan" "Wife"
 *   node scripts/make-codes.mjs "Dheepan:harbour-lamp" "Wife:paper-kite"
 *
 * Then apply the generated file:
 *   npx wrangler d1 execute pip-by-pip --local  --file=./seed.sql
 *   npx wrangler d1 execute pip-by-pip --remote --file=./seed.sql
 */
import { webcrypto as crypto } from 'node:crypto';
import { writeFileSync } from 'node:fs';

const ADJECTIVES = ['amber', 'quiet', 'copper', 'harbour', 'paper', 'winter', 'olive', 'slate', 'ember', 'linen'];
const NOUNS = ['lantern', 'kite', 'sparrow', 'anchor', 'meadow', 'compass', 'thistle', 'willow', 'pebble', 'beacon'];

const salt = process.env.AUTH_SALT ?? 'pip-by-pip-dev-salt';

function pick(list) {
  return list[crypto.getRandomValues(new Uint32Array(1))[0] % list.length];
}

function inventCode() {
  const number = (crypto.getRandomValues(new Uint32Array(1))[0] % 90) + 10;
  return `${pick(ADJECTIVES)}-${pick(NOUNS)}-${number}`;
}

function normaliseCode(code) {
  return code.trim().toLowerCase().replace(/[\s_]+/g, '-').replace(/-+/g, '-');
}

async function hashCode(code) {
  const bytes = new TextEncoder().encode(`${salt}:${normaliseCode(code)}`);
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');
}

function idFor(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'learner';
}

const args = process.argv.slice(2);
const people = (args.length ? args : ['Dheepan', 'Wife']).map((arg) => {
  const [name, code] = arg.split(':');
  return { name: name.trim(), code: code ? normaliseCode(code) : inventCode() };
});

const recoveryCode = process.env.RECOVERY_CODE ? normaliseCode(process.env.RECOVERY_CODE) : `recovery-${inventCode()}`;

const rows = [];
const now = Date.now();

for (const person of people) {
  rows.push({ id: idFor(person.name), name: person.name, code: person.code, recovery: 0 });
}
rows.push({ id: 'recovery', name: 'Recovery', code: recoveryCode, recovery: 1 });

let sql = '-- Generated by scripts/make-codes.mjs. Safe to commit: it holds hashes, not codes.\n';
sql += 'DELETE FROM learners;\n';

for (const row of rows) {
  const hash = await hashCode(row.code);
  sql += `INSERT INTO learners (id, name, code_hash, is_recovery, created_at) VALUES ('${row.id}', '${row.name.replace(/'/g, "''")}', '${hash}', ${row.recovery}, ${now});\n`;
}

writeFileSync(new URL('../seed.sql', import.meta.url), sql);

const width = Math.max(...rows.map((row) => row.name.length));
console.log('\n  Sign-in codes for Pip by Pip. These are shown once.\n');
for (const row of rows) {
  console.log(`    ${row.name.padEnd(width)}   ${row.code}`);
}
console.log('\n  Written to seed.sql. Apply it with:\n');
console.log('    npx wrangler d1 execute pip-by-pip --local  --file=./seed.sql');
console.log('    npx wrangler d1 execute pip-by-pip --remote --file=./seed.sql\n');
console.log('  Note: hashes depend on AUTH_SALT. Use the same salt locally and in production.\n');
